=== aradan04/40260_/XML/alumno.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="alumnos"> 
    <complexType>
      <sequence>
        <element name="alumno" maxOccurs="unbounded"> <complexType>
            <sequence>
              <element name="nombre" type="string" />
              <element name="nacimiento" type="date" />
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== aradan04/40260_/XML/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="alumno.xsd">
    
    <alumno>
        <nombre>Eren</nombre>
        <nacimiento>0845-03-30</nacimiento>
    </alumno>

    <alumno>
        <nombre>Mikasa</nombre>
        <nacimiento>0835-02-10</nacimiento>
    </alumno>

    <alumno>
        <nombre>Armin</nombre>
        <nacimiento>0834-11-03</nacimiento>
    </alumno>

</alumnos>
